# Configuration for the snippet-bot
snippet-bot:
  enabled: true
  snippetPaths:
    - "samples/snippets/**/*.java"
    - "samples/snippets/**/*.kt"
    - "samples/snippets/**/*.py"
    - "samples/snippets/**/*.js"
    - "samples/snippets/**/*.ts"
    - "samples/snippets/**/*.go"
    - "samples/snippets/**/*.rb"
    - "samples/snippets/**/*.php"
    - "samples/snippets/**/*.cs"
    - "samples/snippets/**/*.cpp"
    - "samples/snippets/**/*.swift"
    - "samples/snippets/**/*.sh"
    - "samples/snippets/**/*.yaml"
    - "samples/snippets/**/*.yml"
    - "samples/snippets/**/*.json"
    - "samples/snippets/**/*.xml"
    - "samples/snippets/**/*.html"
    - "samples/snippets/**/*.css"
    - "samples/snippets/**/*.scss"
    - "samples/snippets/**/*.md"
    - "samples/snippets/**/*.txt"
    - "samples/snippets/**/*.proto"
    - "samples/snippets/**/*.avdl"
    - "samples/snippets/**/*.thrift"
    - "samples/snippets/**/*.graphql"
    - "samples/snippets/**/*.sql"
    - "samples/snippets/**/*.r"
    - "samples/snippets/**/*.pl"
    - "samples/snippets/**/*.pm"
    - "samples/snippets/**/*.bat"
    - "samples/snippets/**/*.ps1"
    - "samples/snippets/**/*.dockerfile"
    - "samples/snippets/**/*.makefile"
    - "samples/snippets/**/*.gradle"
    - "samples/snippets/**/*.properties"
    - "samples/snippets/**/*.ini"
    - "samples/snippets/**/*.conf"
    - "samples/snippets/**/*.cfg"
    - "samples/snippets/**/*.toml"
    - "samples/snippets/**/*.lock"
    - "samples/snippets/**/*.log"
    - "samples/snippets/**/*.out"
    - "samples/snippets/**/*.err"
    - "samples/snippets/**/*.pid"
    - "samples/snippets/**/*.pidfile"
    - "samples/snippets/**/*.pid.lock"
    - "samples/snippets/**/*.pidfile.lock"
    - "samples/snippets/**/*.pid.lockfile"
    - "samples/snippets/**/*.pidfile.lockfile.lock"
    - "samples/snippets/**/*.pid.lockfile.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pid.lockfile.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock.lock"
    - "samples/snippets/**/*.pidfile.lockfile.lock.lock
